### ISSUE TITLE
Optional: try to align texts according to design

### ISSUE THREAD

**Issue by rudnitskih** [scandy5/email#3]
Issue 1:
<img width="216" alt="screen shot 2018-10-07 at 16 13 57" src="https://user-images.githubusercontent.com/8848858/46582208-0d0bc300-ca4c-11e8-9e02-9b29436f6c7d.png">

Issue 2:
<img width="661" alt="screen shot 2018-10-07 at 16 14 54" src="https://user-images.githubusercontent.com/8848858/46582220-257bdd80-ca4c-11e8-9b96-82babe59f1b5.png">

**Comment by scandy5** [comment]
issue 2, там где заказы, у меня вроде так же как и на макете, а первое сделал
